"use client";

import { useEffect, useMemo, useState } from "react";
import { rallyConcepts } from "./catalog";
import { originals } from "./originals";

type Review = { id: string; reviewerName: string; rating: number; body: string };
type Stat = { runs: number; reviewCount: number; averageRating: number | null; reviews: Review[] };
type CommunityListing = { id: string; name: string; creatorName: string; outcome: string; proof: string; accessModel: "free" | "paid"; priceCents: number; sourceUrl: string | null };

export default function Home() {
  const [stats, setStats] = useState<Record<string, Stat>>({});
  const [listings, setListings] = useState<CommunityListing[]>([]);
  const [marketStatus, setMarketStatus] = useState("");
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("All");
  const categories = useMemo(() => ["All", ...new Set(rallyConcepts.map((item) => item.category))], []);
  const visibleRallies = useMemo(() => rallyConcepts.filter((item) => {
    const haystack = `${item.title} ${item.category} ${item.forWhom} ${item.promise}`.toLowerCase();
    return (category === "All" || item.category === category) && haystack.includes(search.trim().toLowerCase());
  }), [category, search]);

  useEffect(() => {
    fetch("/api/marketplace").then((response) => response.ok ? response.json() : null).then((data) => { if (data) { setStats(data.stats ?? {}); setListings(data.listings ?? []); } });
  }, []);

  async function buyListing(id: string) {
    setMarketStatus("Opening secure checkout…");
    const response = await fetch("/api/checkout", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ creatorAppId: id }) });
    const data = await response.json();
    if (response.status === 401 && data.signIn) { window.location.href = data.signIn; return; }
    if (response.ok && data.url) { window.location.href = data.url; return; }
    setMarketStatus(data.error ?? "Checkout could not be opened.");
  }

  return <main className="consumer-home">
    <nav className="store-nav"><a href="#top" className="brand"><span className="brand-mark">P</span>Pep Rally</a><div className="nav-links"><a href="#marketplace">Shop</a><a href="#free">Try free</a><a href="#creators">For creators</a><a href="#faq">FAQ</a></div><a className="nav-button center-link" href="/library">Sign in / My Rallies</a></nav>

    <section className="shop-hero" id="top"><div className="shop-hero-copy"><span className="eyebrow">THE MARKETPLACE FOR EVERYDAY MINI-APPS</span><h1>Someone solved it.<br/><em>Now you can use it.</em></h1><p>Shop working apps that turn your information into something finished: a plan, a decision, a study system, a priced product, or an organized next step.</p><div><a className="primary" href="#marketplace">Shop Rallies</a><a className="text-button" href="#creators">Make money from what you built →</a></div></div><div className="shop-hero-images" aria-label="Free Bachelorette and garden Rallies"><figure><img src="/rallies/bachelorette-pool.jpg" alt="Friends planning a sunny weekend together"/><figcaption><b>Bachelorette Blueprint</b><span>FREE · WORKING APP · SAVED OUTCOME</span></figcaption></figure><figure><img src="/rallies/lush-garden.jpg" alt="A lush raised-bed and container garden"/><figcaption><b>Little Garden Planner</b><span>FREE · LIVE WEATHER · SAVED PLAN</span></figcaption></figure></div></section>

    <section className="consumer-proof"><span><b>Open</b> the working app</span><span><b>Finish</b> something useful</span><span><b>Keep</b> your saved result</span></section>

    <section className="storefront" id="free"><header><small>FREE · READY TO USE</small><h2>Try a complete Rally.</h2><p>Choose one, sign in, add your real information, finish the outcome, and keep your work. These are usable apps—not idea pages.</p></header><div className="product-grid">{originals.map((product) => { const stat = stats[product.slug] ?? { runs: 0, reviewCount: 0, averageRating: null, reviews: [] }; return <article className={`product-card ${product.color}`} key={product.slug}><div className="product-photo"><img src={product.image} alt=""/><span>{product.price}</span></div><div className="product-copy"><small>{product.eyebrow}</small><h3>{product.title}</h3><p>{product.blurb}</p><ul>{product.included.map((item) => <li key={item}>{item}</li>)}</ul><div className="product-stats"><span>{stat.runs} saved plan{stat.runs === 1 ? "" : "s"}</span><span>{stat.averageRating ? `★ ${stat.averageRating.toFixed(1)} from ${stat.reviewCount}` : "New · no reviews yet"}</span></div><a className="primary full center-link" href={`/shop/${product.slug}`}>Open the free Rally →</a></div></article>; })}</div></section>

    <section className="community-marketplace" id="marketplace"><header><div><small>SHOP THE MARKETPLACE</small><h2>Small apps. Real outcomes.</h2><p>Choose the job you need to finish. Every working Rally opens as a usable mini-site and lets you save the result or download it as Markdown.</p></div><a href="/library">Go to My Rallies →</a></header>{listings.length > 0 && <><div className="ready-divider"><span>FROM PEP RALLY CREATORS</span><p>Published by real people and checked for a working outcome.</p></div><div className="community-grid">{listings.map((listing, index) => <article key={listing.id} className={`community-card tone-${index % 4}`}><div className="community-card-top"><span>Made by {listing.creatorName}</span><b>{listing.accessModel === "free" ? "Free" : `$${(listing.priceCents / 100).toFixed(0)}`}</b></div><div className="community-icon">{listing.name.slice(0, 1).toUpperCase()}</div><h3>{listing.name}</h3><p>{listing.outcome}</p><small>{listing.proof}</small>{listing.accessModel === "free" && listing.sourceUrl ? <a className="primary center-link" href={listing.sourceUrl} target="_blank" rel="noreferrer">Open free Rally →</a> : <button className="primary" onClick={() => buyListing(listing.id)}>Get this Rally · ${(listing.priceCents / 100).toFixed(0)}</button>}</article>)}</div></>}<div className="ready-divider"><span>WORKING RALLIES · OPEN ONE</span><p>Add your information, create the result, save it, and download prompts to customize the app further.</p></div><div className="discovery-tools"><label><span>Search by problem or person</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Try nursing, pricing, travel, roommates…"/></label><div>{categories.map((item) => <button className={category === item ? "active" : ""} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div></div><div className="idea-grid">{visibleRallies.map((rally) => <a href={`/rally/market/${rally.slug}`} className={`idea-card idea-${rally.accent}`} key={rally.slug}><div><span>{rally.monogram}</span><small>{rally.category} · ${(rally.priceCents / 100).toFixed(0)}</small></div><h3>{rally.title}</h3><p>{rally.promise}</p><b>Open this Rally →</b></a>)}</div>{!visibleRallies.length && <div className="no-ideas"><b>No exact match yet.</b><p>That may be the Rally someone needs to make.</p><a href="#creators">Publish it →</a></div>}{marketStatus && <p className="market-status">{marketStatus}</p>}</section>

    <section className="what-you-get buyer-path"><div><small>FOR PEOPLE SHOPPING</small><h2>Buy the app.<br/><em>Keep the outcome.</em></h2><p>You are paying for a usable mini-app and the result it helps you finish—not a folder of setup instructions. Any PDF, calendar, CSV, link, or Markdown export supports that outcome.</p><a className="primary center-link" href="#marketplace">Find a Rally →</a></div><div className="get-list"><span><b>1 · The working app</b>Open it without assembling code or integrations.</span><span><b>2 · Your workspace</b>Keep your inputs, choices, and progress together.</span><span><b>3 · The promised result</b>Finish the plan, decision, calculation, or study system.</span><span><b>4 · The next action</b>Share, export, book, message, pay, or return later.</span></div></section>

    <section className="marketplace-trust"><div className="trust-summary"><p className="kicker">THE PEP RALLY BUYER PROMISE</p><h2>Know what it does before you pay.</h2><p>Every full listing should show the inputs, finished outcome, permissions, maker, update history, support, and real reviews. Paid Rallies must open and match their listing or the buyer can request marketplace review.</p><div className="trust-numbers"><span><b>Try the outcome</b>See a working preview before checkout</span><span><b>No mystery</b>Data and outside services are disclosed up front</span><span><b>Human say</b>Messages, bookings, payments, and high-stakes choices stay with you</span></div></div><div className="trust-checklist"><small>WHAT A COMPLETE LISTING SHOWS</small><span>01 · A clear one-sentence outcome</span><span>02 · A working demo or realistic preview</span><span>03 · What you bring and what you receive</span><span>04 · Permissions, sources, and human decisions</span><span>05 · Price, support, updates, and refund expectations</span><span>06 · Verified usage and reviews—never invented numbers</span></div></section>

    <section className="outcome-standard"><header><small>WHAT COUNTS AS A RALLY</small><h2>Open it. Finish something. Keep the result.</h2><p>The subjects can be broad. The customer outcome cannot be vague.</p></header><div><article><b>01</b><h3>Bring real context</h3><p>Your dates, notes, measurements, budget, constraints, preferences, or source material.</p></article><article><b>02</b><h3>Get a first useful result</h3><p>Not an empty dashboard—a plan, comparison, study system, calculation, shortlist, or decision draft.</p></article><article><b>03</b><h3>Review and decide</h3><p>Change assumptions, correct mistakes, and keep the important human judgment with you.</p></article><article><b>04</b><h3>Use it outside the app</h3><p>Save the workspace, return later, share it, export it, or take the next real-world action.</p></article></div></section>

    <section className="creator-path" id="creators"><div><small>FOR PEOPLE WHO MAKE THINGS</small><h2>Made something useful?<br/><em>Put it on the shelf.</em></h2><p>Turn a tool you made for yourself, your clients, your students, or your community into a Rally people can try and buy.</p><a className="primary center-link" href="/build">Build or publish a Rally →</a></div><aside><small>EXAMPLE $20 SALE</small><span><b>$16</b>to the creator</span><span><b>$4</b>to Pep Rally</span><p>The current marketplace model sends 80% of a sale to the creator before outside processing costs. Your listing shows the price, outcome, and what customers receive.</p></aside></section>

    <section className="simple-how"><header><small>WHAT PEP RALLY ADDS</small><h2>Your expertise, packaged<br/>as something people can use.</h2></header><div><article><b>01</b><h3>Build it or bring it</h3><p>Start inside Pep Rally, or upload and link the mini-app you already made.</p></article><article><b>02</b><h3>Add the hard parts</h3><p>Accounts, hosting, payments, files, live data, messages, calendars, maps, AI, and support.</p></article><article><b>03</b><h3>Show the outcome</h3><p>Give shoppers a working preview, clear permissions, price, and exactly what they receive.</p></article><article><b>04</b><h3>Sell and improve</h3><p>Reach customers, collect verified reviews, see usage, and publish updates.</p></article></div></section>

    <section className="builder-invite"><div><small>TWO WAYS TO PUBLISH</small><h2>Build it here.<br/><em>Or bring it with you.</em></h2><p>Either path ends with the same thing: a working Rally shoppers can understand, try, buy, and keep.</p><a className="primary" href="/build">Build This Rally →</a></div><div className="builder-invite-list"><span><b>Build inside Pep Rally</b>Shape the person, problem, inputs, decisions, and outcome.</span><span><b>Upload what you made</b>Bring a live URL, mini-app, code project, or prototype.</span><span><b>Make it launchable</b>Add the connections and customer protections it needs.</span><span><b>Reach the marketplace</b>Choose free or paid, publish, learn, and improve.</span></div></section>

    <section className="consumer-faq" id="faq"><header><small>PEP RALLY FAQ</small><h2>Shop a Rally.<br/>Or sell one.</h2></header><div><details open><summary>What exactly is Pep Rally?</summary><p>Pep Rally is a two-sided marketplace for focused mini-apps. Shop a working solution to an everyday problem, or publish and sell one you made.</p></details><details><summary>What do I get when I pay?</summary><p>The working mini-app, your private saved workspace, the promised outcome, and any exports or future updates shown in the listing.</p></details><details><summary>Can I try a Rally first?</summary><p>Yes. Start with the two free complete Rallies, or use the working preview on a paid listing before checkout.</p></details><details><summary>How do creators make money?</summary><p>Creators choose free or paid access. The current model gives the creator 80% of each sale before outside processing costs, plus a listing, customer library, verified reviews, usage signals, and updates.</p></details><details><summary>Do I have to build it inside Pep Rally?</summary><p>No. Build from an idea inside Pep Rally, link a mini-app that is already live, or upload an existing project for hosting.</p></details><details><summary>Why do I sign in?</summary><p>Your account keeps your Rallies, plans, purchases, and saved progress private and available when you return. Pep Rally currently uses secure ChatGPT sign-in.</p></details></div></section>

    <footer className="consumer-footer"><a href="#top" className="brand"><span className="brand-mark">P</span>Pep Rally</a><p>Working apps, made by people who know the problem.</p><div><a href="#marketplace">Shop</a><a href="#creators">Sell your Rally</a></div><span>Open. Finish. Keep.</span></footer>
  </main>;
}
