export const metadata = { title: "Trust, support, and marketplace terms · Pep Rally", description: "How Pep Rally handles previews, purchases, privacy, refunds, support, and creator responsibilities." };

export default function PoliciesPage() {
  return <main className="policy-page">
    <nav><a href="/" className="brand"><span className="brand-mark">P</span>Pep Rally</a><div><a href="/#marketplace">Shop</a><a href="/build">Sell a Rally</a><a href="/library">My Rallies</a></div></nav>
    <header><small>PEP RALLY TRUST CENTER</small><h1>Useful products.<br/><em>Clear responsibilities.</em></h1><p>These launch-edition terms explain what buyers and creators can expect while Pep Rally is operating as a limited test marketplace.</p><span>Effective September 15, 2026 · Launch edition</span></header>
    <section className="policy-grid">
      <article><small>BUYER PROMISE</small><h2>The Rally should match its listing.</h2><p>You should be able to open the promised working experience, understand what information it uses, and produce the result described before checkout.</p><ul><li>Paid access is tied to your signed-in account.</li><li>Outside prices, availability, and policies remain the provider’s source of truth.</li><li>You approve messages, bookings, payments, and high-stakes decisions.</li></ul></article>
      <article><small>REFUNDS</small><h2>Ask for review when the product fails.</h2><p>Request a marketplace review if a paid Rally does not open, materially differs from its listing, or cannot create the promised outcome.</p><ul><li>Contact the person who invited you to this private test within 14 days.</li><li>Include the Rally name and what failed; never send passwords or secret keys.</li><li>Approved test-market refunds are returned through the original payment method.</li></ul></article>
      <article><small>PRIVACY</small><h2>Your workspace is not marketplace content.</h2><p>Saved Rally inputs and results are private to the signed-in account unless you deliberately share or send them through an outside service.</p><ul><li>Creators do not automatically receive buyer workspace contents.</li><li>Uploaded creator source files are stored privately for launch review.</li><li>Do not upload health records, financial credentials, or content you do not have permission to use.</li></ul></article>
      <article><small>CREATOR RESPONSIBILITY</small><h2>Only sell what you can support.</h2><p>Creators must accurately describe the outcome, disclose outside services and permissions, own or license their content, and keep the working version available.</p><ul><li>No fabricated usage, testimonials, credentials, or guarantees.</li><li>Unsafe, deceptive, infringing, or unusable listings may be removed.</li><li>Real creator payouts require identity review and Stripe Connect before activation.</li></ul></article>
      <article id="support"><small>REPORTING + SUPPORT</small><h2>Tell us what went wrong.</h2><p>During this private test, contact the person who shared Pep Rally with you. Include the listing URL and a concise description of the broken, misleading, unsafe, or infringing behavior.</p><div className="policy-actions"><a className="primary" href="/connections">Check service status</a><a href="/library">Return to My Rallies</a></div></article>
      <article><small>PAYMENTS</small><h2>The current site uses Stripe sandbox mode.</h2><p>No real money moves in this hosted prototype. Before public commerce, Pep Rally must activate production payments, creator onboarding, payouts, tax handling, chargebacks, and operational support.</p><a href="/connections">See connection status →</a></article>
    </section>
    <footer><p>This is a concise launch-edition policy—not a substitute for jurisdiction-specific legal advice before commercial release.</p><a href="/">Return to Pep Rally →</a></footer>
  </main>;
}
